#!/bin/bash

echoerr() { echo "$@" 1>&2; }
if [ $# -eq 1 ]
then
   echo "$@"
else
   echo "usage is License <path_to_properties_file>"
   exit;
fi

BUILD_DIR="$( dirname "$0" )/../../../target"
MVN_GENERATED_PATH="$BUILD_DIR/mvn-generated-runtime-classpath"
if [ -f "$MVN_GENERATED_PATH" ]; then
  # development launch mode
  #echoerr "Setting classpath from: $MVN_GENERATED_PATH"
  DT_CORE_JAR=`ls $BUILD_DIR/dt-stram-*.jar | grep -v tests`
  if [ ! -f "$DT_CORE_JAR" ]; then
    echoerr "Error: Cannot find $DT_CORE_JAR";
    exit 1;
  fi
  DT_CLASSPATH="$DT_CLASSPATH:$DT_CORE_JAR"
else
  MVN_GENERATED_PATH="$( dirname "$0" )/mvn-generated-runtime-classpath"
  if [ ! -f "$MVN_GENERATED_PATH" ]; then
    echoerr "Error: Cannot find $MVN_GENERATED_PATH (has $( cd $(dirname $0)/..; pwd -P )/install.sh run?)";
    exit 1;
  fi
fi

DT_CLASSPATH=$DT_CLASSPATH:`cat $MVN_GENERATED_PATH`

if [ "$DT_CLASSPATH" != "" ]; then
  if test -z "$HADOOP_CLASSPATH"
  then
    export HADOOP_CLASSPATH=$DT_CLASSPATH
  else
    export HADOOP_CLASSPATH=$HADOOP_CLASSPATH:$DT_CLASSPATH
  fi
fi

if [ "$DT_CLIENT_OPTS" = "" ]; then
  DT_CLIENT_OPTS=-Xmx1024m
fi

export HADOOP_CLIENT_OPTS="$DT_CLIENT_OPTS"

export CLASSPATH=$DT_CLASSPATH
java $DT_CLIENT_OPTS com.datatorrent.stram.license.License "$@"

