#!/bin/bash

BUILD_DIR="$( dirname "$0" )/../../../target"
MVN_GENERATED_PATH="$BUILD_DIR/mvn-generated-runtime-classpath"
if [ -f "$MVN_GENERATED_PATH" ]; then
  # development launch mode  
  echo "Setting classpath from: $MVN_GENERATED_PATH"
  STRAM_CORE_JAR="$BUILD_DIR/malhar-stram-0.1-SNAPSHOT.jar"
  if [ ! -f "$STRAM_CORE_JAR" ]; then
    echo "Error: Cannot find $STRAM_CORE_JAR";
    exit 1;
  fi 
  STRAM_CLASSPATH="$STRAM_CLASSPATH:$STRAM_CORE_JAR"
else
  MVN_GENERATED_PATH="$( dirname "$0" )/mvn-generated-runtime-classpath"
  if [ ! -f "$MVN_GENERATED_PATH" ]; then
    echo "Error: Cannot find $MVN_GENERATED_PATH (has $( cd $(dirname $0)/..; pwd -P )/install.sh run?)";
    exit 1;
  fi
fi

STRAM_CLASSPATH=$STRAM_CLASSPATH:`cat $MVN_GENERATED_PATH`
#echo "$STRAM_CLASSPATH"

if [ "$STRAM_CLASSPATH" != "" ]; then
  if test -z "$HADOOP_CLASSPATH"
  then
    export HADOOP_CLASSPATH=$STRAM_CLASSPATH
  else
    export HADOOP_CLASSPATH=$HADOOP_CLASSPATH:$STRAM_CLASSPATH
  fi
fi

if [ "$STRAM_CLIENT_OPTS" = "" ]; then
  STRAM_CLIENT_OPTS=-Xmx1024m
fi

export HADOOP_CLIENT_OPTS="$STRAM_CLIENT_OPTS"

if [ "$HADOOP_PREFIX" = "" ]; then
  echo "Warning: HADOOP_PREFIX is not set, running standalone."
  export CLASSPATH=$STRAM_CLASSPATH
  java $STRAM_CLIENT_OPTS com.malhartech.stram.cli.StramCli 
else
  # mask duplicate slf4j binding
  export HADOOP_CLASSPATH=${HADOOP_CLASSPATH/slf4j-log4j12-1.7.1.jar/slf4j-log4j12-DUPBINDING.jar}
#  $HADOOP_PREFIX/bin/hadoop classpath
  $HADOOP_PREFIX/bin/hadoop com.malhartech.stram.cli.StramCli
fi

