#!/bin/bash

if [ "$HADOOP_PREFIX" = "" ]; then
    echo "Error: HADOOP_PREFIX is not set."
    exit 1
fi

function addhc
{
  if test -z "$HADOOP_CLASSPATH"
  then
    export HADOOP_CLASSPATH=~/.m2/repository/$1
  else 
    export HADOOP_CLASSPATH=$HADOOP_CLASSPATH:~/.m2/repository/$1
  fi
}

addhc com/malhartech/malhar-bufferserver/0.1-SNAPSHOT/malhar-bufferserver-0.1-SNAPSHOT.jar
addhc com/malhartech/malhar-stram/0.1-SNAPSHOT/malhar-stram-0.1-SNAPSHOT.jar
addhc com/esotericsoftware/kryo/kryo/2.19/kryo-2.19.jar
addhc com/esotericsoftware/reflectasm/reflectasm/1.07/reflectasm-1.07-shaded.jar
addhc com/esotericsoftware/minlog/minlog/1.2/minlog-1.2.jar
addhc com/sun/jersey/jersey-client/1.8/jersey-client-1.8.jar
addhc org/mockito/mockito-all/1.8.5/mockito-all-1.8.5.jar
addhc io/netty/netty-transport/4.0.0.Alpha2/netty-transport-4.0.0.Alpha2.jar
addhc io/netty/netty-common/4.0.0.Alpha2/netty-common-4.0.0.Alpha2.jar
addhc io/netty/netty-buffer/4.0.0.Alpha2/netty-buffer-4.0.0.Alpha2.jar
addhc io/netty/netty-codec/4.0.0.Alpha2/netty-codec-4.0.0.Alpha2.jar


if [ "$STRAM_CLIENT_OPTS" = "" ]; then
  STRAM_CLIENT_OPTS=-Xmx1024m
fi

export HADOOP_CLIENT_OPTS="$STRAM_CLIENT_OPTS"

$HADOOP_PREFIX/bin/hadoop com.malhartech.stram.cli.StramCli 
